repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        files: ^src/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --fix]
        files: ^src/
      - id: ruff-format
        args: [--config=pyproject.toml]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^src/
